### ISSUE TITLE
Invalid date in dayHeaderContent args [only dateGridMonth]

### ISSUE THREAD

**Issue by maksymrudiuk** [fullcalendar/fullcalendar-react#157]
I have next bug.
The date arg in dayHeaderContent callback for dateGridMonth has weird value (1970 date)

Sandbox https://codesandbox.io/s/holy-rgb-r2nrg

Side-effect: If user has GMT with minus DayGridMonth has shifted days.

**Comment by acerix** [comment]
Since that header applies to multiple dates, it does not have a specific date, so the only data in `date` is the day of the week.  There's an open issue regarding this:

https://github.com/fullcalendar/fullcalendar/issues/5854
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
