### ISSUE TITLE
onContextMenu callback set in eventContent does not fire

### ISSUE THREAD

**Issue by chunyinli** [fullcalendar/fullcalendar-react#158]
In 5.10.0, attaching a `onContextMenu` event on the content of eventContent no long fire if the eventClick option is passed in to FullCalendar. If eventClick option is not used then it works. It works either way in version 5.9.0. Appears to be specific to fullcalendar-react.

Reduced test case: https://codesandbox.io/s/fullcalendar-eventcontent-oncontextmenu-5-10-0-fyt9p

Interestingly, if the `onContentMenu` is attached to a button instead of a div, then it kinda works.

Example that shows it works in standard fullcalendar: https://codesandbox.io/s/fullcalendar-contentmenu-event-works-b5c00?file=/src/index.js

**Comment by acerix** [comment]
It looks like it could be a bug specific to this React component, but should work better to attach the callbacks in `eventDidMount` instead of `eventContent`.

**Comment by chunyinli** [comment]
Good idea, definite look into attaching the event in `eventDidMount`, thanks.

**Comment by arshaw** [comment]
I'm nearly certain the root cause is this bug:
https://github.com/fullcalendar/fullcalendar/issues/5963
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

The reason it's only happening in the React implementation (and not vanilla JS) is that React does event bubbling differently ([see here](https://www.freecodecamp.org/news/event-propagation-event-bubbling-event-catching-beginners-guide/#how-event-bubbling-happens-in-react)).

Anyway, solving #5963 will likely fix this too
