### ISSUE TITLE
Full Calendar Scheduler via SharePoint Framework (REACT)

### ISSUE THREAD

**Issue by farhanfaiz** [fullcalendar/fullcalendar-react#31]
I am trying to create a SharePoint Framework webpart (based on REACT) using [FullCalendar Scheduler](https://fullcalendar.io/docs/react). Full Calendar React daygrid works but as soon as I import Scheduler addon (@fullcalendar/resource-timeline), build failed with following error:

**The expected type comes from property 'plugins' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes & Readonly & Readonly<{ children?: ReactNode; }>**

import * as React from 'react'
import FullCalendar from '@fullcalendar/react'
import dayGridPlugin from '@fullcalendar/daygrid'
import timeGridPlugin from '@fullcalendar/timegrid'
import resourceTimelinePlugin from '@fullcalendar/resource-timeline'

import '@fullcalendar/core/main.css';
import '@fullcalendar/daygrid/main.css';
import '@fullcalendar/timegrid/main.css';

export default class MyCall extends React.Component {
    render() {
      return (
        <FullCalendar 
            defaultView="dayGridMonth"             
            header={{
              left: 'prev,next today',
              center: 'title',
              right: 'dayGridMonth,timeGridWeek,timeGridDay'
            }}
            plugins={[ dayGridPlugin, timeGridPlugin, resourceTimelinePlugin ]} />
      )
    }  
  }

If I remove the import statement for @fullcalendar/resource-timeline, it works fine but as soon as I add the import statement for scheduler, build error generated

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just began triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

If you still have an error, please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
