### ISSUE TITLE
Re-Rendering of eventRender on every component change in fullcalendar 4.3.0

### ISSUE THREAD

**Issue by js-chris** [fullcalendar/fullcalendar-react#32]
Hi,

I have the problem that the FullCalendar component with defined eventRender prop re-renders even if none of the props of FullCalendar changes.

Background is, that I add a button with menu and a longDescription to every event. But if I just open the menu or open an editor for the event  (in a modal), every event is re-rendered, which makes rendering quite slow and you can't rely on a dom element.

Is it possible to prevent FullCalendar to re-render all the events during component update / change?

thx
Chris

**Comment by quorak** [comment]
I can see the same behaviour with a simple `eventMouseEnter` handler, which changes a surrounding component. Each render will rerender the fullcalender component and even refetches eventSources.

**Comment by omarragi** [comment]
Any plans for this one ?

**Comment by janchimugica** [comment]
I am also having this issue. If the Calendar component state gets updated, even if it's a piece of state not related to the Calendar (Modal pop-up via Portals), the whole calendar re-renders, which as @quorak mentioned refetches all events.

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just began triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

I believe this discussion covers the issue you mentioned:
https://github.com/fullcalendar/fullcalendar-react/issues/65
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

Otherwise please provide a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
