### ISSUE TITLE
Events out of sync with react state

### ISSUE THREAD

**Issue by Phibedy** [fullcalendar/fullcalendar-react#33]
### Bug Reports
If you drag and drop an event, the event is changed in the FullCalendar itself, even if you don't modify the passed events. This makes sense for non-react applications where you don't have a state, but I don't like that behavior in react.

**Comment by mostlyfabulous** [comment]
Same underlying problem from these issues:
#47 and #54

**Comment by arshaw** [comment]
I believe this issue is related to improper state management between React and FullCalendar. This sort of state-management stuff is easy to get wrong because the FullCalendar docs have not defined any best practices. I have written a doc proposing two standard techniques. Could you please take a look at it and write a comment, or at least a 👍 ? I REALLY REALLY appreciate fast feedback because I'm trying to get this nailed down for the v5 release in the next few days!

Proposal: [Event-data conventions!?](https://github.com/fullcalendar/fullcalendar-react/issues/65)

PS- apologies for [neglecting this repo](https://github.com/fullcalendar/fullcalendar-react/issues/66)
