### ISSUE TITLE
header prev next callback method

### ISSUE THREAD

**Issue by Sankalp-Saxena** [fullcalendar/fullcalendar-react#36]
Hi i need help for prev and next month click callback methods in react.js

**Comment by rashid-02** [comment]
@Sankalp-Saxena Try this under eventRender props of the Fullcalendar.
events={(fetchInfo, successCallback, failureCallback) =>
                    getCalendarData(fetchInfo, successCallback, failureCallback)
                  }

**Comment by yertech** [comment]
> @Sankalp-Saxena Try this under eventRender props of the Fullcalendar.
> events={(fetchInfo, successCallback, failureCallback) =>
> getCalendarData(fetchInfo, successCallback, failureCallback)
> }

Hi, 
I struggle with your code because even if my function return events they are not displayed...

`const Calendar = () => {
  //date of the day
  var d = new Date();
  var n = d.toISOString();

  const [events, setEvents] = useState([]);
  const [calendarDate, setCalendarDate] = useState(n);
  const [instructorModel, setInstructorModel] = useState({
    instructorId: 172,
    date: calendarDate
  });

  useEffect(() => {
    getMonthCourses(instructorModel).then(_courses =>
      setEvents(
        _courses.map(course => {
          return {
            id: course.courseId,
            title: course.name,
            start: course.startDate,
            end: course.endDate,
            description: course.description
          };
        })
      )
    );
  }, [instructorModel]);

  function getCalendarData(fetchInfo) {
    var d = new Date(fetchInfo.startStr);
    setCalendarDate(d.toISOString());
    return events;
  }

  return (
    <FullCalendar
      header={{
        left: "prev,next ",
        center: "title",
        right: "today"
      }}
      defaultView="dayGridMonth"
      plugins={[dayGridPlugin, timeGridPlugin]}
      eventRender={info => console.log(info)}
      events={(fetchInfo, successCallback, failureCallback) => {
        var datas = getCalendarData(fetchInfo);
        if (datas.length > 0) {
//datas conains element
console.log(datas)
          return datas;
        }
      }}
    />
  );
};`

Console.log : (4) [{…}, {…}, {…}, {…}]
example:
1: {id: 7333, title: "title", start: "2020-03-25T15:00:00", end: "2020-03-25T15:00:00", description: "description"}

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just began triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3521
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
