### ISSUE TITLE
Error occured when fetching API data on prev/next click of the calendar

### ISSUE THREAD

**Issue by rashid-02** [fullcalendar/fullcalendar-react#41]
There is an issue or bug occuring when I try to get API data on prev/next click of the calendar and after that calendar becomes fully unresponsive.

error is: TypeError: Cannot read property 'daysOfWeek' of undefined.
Kindly anyone give solution on this.

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just began triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

If there is still an issue, please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/). Would really appreciate it because the time saved reproducing will be time spent fixing.
