### ISSUE TITLE
Set businessHours on eventSource response

### ISSUE THREAD

**Issue by RaphRamos** [fullcalendar/fullcalendar-react#44]
I'm trying to dinamically change the businessHours depending on the week view.
```javascript
   <FullCalendar
      ref={calendarRef}
      defaultView="timeGridWeek"
      plugins={[timeGridPlugin, interactionPlugin]}
      allDaySlot={false}
      weekends={false}
      height="auto"
      nowIndicator={true}
      editable={true}
      selectable={true}
      eventSources={["/blocks?agent_id=2"]}
      eventSourceSuccess={(content, _xhr) => {
        calendarRef.current.calendar.setOption(
          "businessHours",
          content[content.length - 1]
        );
      }}
      eventTimeFormat={{
        hour: "2-digit",
        minute: "2-digit",
        hour12: false
      }}
  />
```
This works fine, as I can see the businessHours been applied. 
The problem is that changing businessHours trigger another render of the calendar, which calls fetch the events again and start an infinite loop.

I used to do this on V3 with jQuery and worked fine.
jQuery code for reference (maybe what I'm doing now is not equivalent):
```javascript
$('#event_calendar').fullCalendar({
    defaultView: 'agendaWeek',
    allDaySlot: false,
    height: 'auto',
    selectable: true,
    events: {
      url: '/blocks?agent_id=2',
      success: function(data, status, response) {
        $('#event_calendar').fullCalendar('option', {
            businessHours: data[data.length -1]
        });
      }
    },
...
});
```

Thanks in advance for any help.

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

It seems the underlying issue is that changing `businessHours` should not refetch events and is not specific to React.  I believe it is covered by this similar issue:
https://github.com/fullcalendar/fullcalendar/issues/4698
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
