### ISSUE TITLE
Calendar view not updating on re-render

### ISSUE THREAD

**Issue by ajitbohra** [fullcalendar/fullcalendar-react#45]
On component, re-rendering changes are reflecting on various parts of UI. Change of view not reflecting.

**Comment by arshaw** [comment]
I believe this issue is related to improper state management between React and FullCalendar. This sort of state-management stuff is easy to get wrong because the FullCalendar docs have not defined any best practices. I have written a doc proposing two standard techniques. Could you please take a look at it and write a comment, or at least a 👍 ? I REALLY REALLY appreciate fast feedback because I'm trying to get this nailed down for the v5 release in the next few days!

Proposal: [Event-data conventions!?](https://github.com/fullcalendar/fullcalendar-react/issues/65)

PS- apologies for [neglecting this repo](https://github.com/fullcalendar/fullcalendar-react/issues/66)

**Comment by ajitbohra** [comment]
@arshaw sure will have a look
