### ISSUE TITLE
State Management Best Practices 

### ISSUE THREAD

**Issue by Justinohallo** [fullcalendar/fullcalendar-react#51]
This may not be the best place for this, but I have not been able to find any resources online. 

The Demo application is a great start, but there are not many resources that show how to properly use the calendar within a large application. I understand that the library was designed for maximum flexibility, but has anyone built a thorough implementation of this library? I have an MVP working, but I would love to discuss the use of Hooks, specifically useState vs useReducer in regards to manipulating the calendar data. 

Has anyone come up with some best practices? Is there a better place to have this conversation? I would love to write a blog or tutorial for going beyond the basic set up as I have ran into some very particular issues with the library that could be documented. 

Cheers,

**Comment by arshaw** [comment]
Hey @Justinohallo, thanks for writing in about this.

This sort of state-management stuff is easy to get wrong because the FullCalendar docs have not defined any best practices. I have written a doc proposing two standard techniques. Could you please take a look at it and write a comment, or at least a 👍 ? I REALLY REALLY appreciate fast feedback because I'm trying to get this nailed down for the v5 release in the next few days!

Proposal: [Event-data conventions!?](https://github.com/fullcalendar/fullcalendar-react/issues/65)

PS- apologies for [neglecting this repo](https://github.com/fullcalendar/fullcalendar-react/issues/66)
