### ISSUE TITLE
Drag and drop broken? onReceiveEvent called twice, duplicate events created

### ISSUE THREAD

**Issue by Ryanauger95** [fullcalendar/fullcalendar-react#54]
Here is a re-creation from another user with the [same issue](https://github.com/fullcalendar/fullcalendar-react/issues/47) here: 

https://codesandbox.io/s/strange-pine-5xkre

Any idea what the issue could be ? Doesn't seem like this is intentional. It seems drag and drop is broken

**Comment by arshaw** [comment]
I believe this issue is related to improper state management between React and FullCalendar. This sort of state-management stuff is easy to get wrong because the FullCalendar docs have not defined any best practices. I have written a doc proposing two standard techniques. Could you please take a look at it and write a comment, or at least a 👍 ? I REALLY REALLY appreciate fast feedback because I'm trying to get this nailed down for the v5 release in the next few days!

Proposal: [Event-data conventions!?](https://github.com/fullcalendar/fullcalendar-react/issues/65)

PS- apologies for [neglecting this repo](https://github.com/fullcalendar/fullcalendar-react/issues/66)
