### ISSUE TITLE
clear out gh-pages

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar-react#6]
Just some housekeeping for this repo: could you clear out everything related to gh-pages?

**Comment by joshuaRuff** [comment]
Just went through the code. I'm not seeing anything still related to gh-pages there.

**Comment by arshaw** [comment]
Sorry, I meant in the github ui. in Code > Environment there's a bunch of stuff. it doesn't matter too much

**Comment by joshuaRuff** [comment]
Ah, okay, I think this is fixed in the repo settings by turning off gh-pages? I don't have access to the settings tab to check if that would fix it. If not,  I did find this article about the environment deployments : https://help.github.com/en/articles/viewing-deployment-activity-for-your-repository

**Comment by arshaw** [comment]
you now have admin access!

**Comment by joshuaRuff** [comment]
The only reference to github pages is in the activity log which to my understanding can't be cleared out.
