### ISSUE TITLE
How to use resourceRender in React?

### ISSUE THREAD

**Issue by vitorlimadev** [fullcalendar/fullcalendar-react#60]
Hello friends! I haven't found any instructions on how to add question issues so I'll try my best to explain.

I want to know if it is possible to use React elements in the resourceRender prop. I've searched in the fullcalendarJS docs and managed to implement that in React, but only using vanilla JS. I wasn't able to render my own React components in the resource.

```
resourceRender={info => {
  const questionMark = document.createElement('strong');
  questionMark.innerText = ' (?) ';

  info.el
    .querySelector('.fc-cell-text')
    .appendChild(Resource);
}}
```

It appends the DOM element directly. I tried doing it with a React component with ".appendChild(Resource);" where Resource is just a plain React functional component with a <p>Hi</p> in it. But I think this isn't possible, it gives me the error "TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'."

Am I doing something wrong? Is this a way to add React components in here this function?
Thank you all a lot for yourr attention and for the amazing work!

**Comment by mostlyfabulous** [comment]
I have a feeling that React elements aren't supported for what you want to do.
You might be interested in reading #12 as it is related to your intentions. You may have to use `ReactDOM.render` to get React components to work.

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

It sounds like this is the same as https://github.com/fullcalendar/fullcalendar-react/issues/12 but for resources instead of events, so I believe what you are looking for is possible in version 5 using `resourceLabelContent`, similar to this example for events:

https://github.com/fullcalendar/fullcalendar-example-projects/blob/v5/react/src/DemoApp.jsx#L39
